WebClient/Models/Interest/CreateInterestModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Socializr.Models.Interest
{
    public class CreateInterestModel
    {
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }
    }
}

WebClient/Models/Interest/EditInterestModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Socializr.Models.Interest
{
    public class EditInterestModel
    {
        public int InterestId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

WebClient/Models/Interest/ViewInterestModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Socializr.Models.Interest
{
    public class ViewInterestModel
    {
        public int InterestId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

WebClient/Controllers/InterestController.cs
using BusinessEntities.Entities;
using BusinessEntities.Enums;
using Socializr.Code.Attributes;
using Socializr.Code.Base;
using Socializr.Code.Pagination;
using Socializr.Models.Interest;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Socializr.Controllers
{
    [AuthorizePermissions(Permissions.ManageLookups)]
    public class InterestController : BaseController
    {
        // GET: Interest
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult List(int pageNumber = 1)
        {
            var resultsNumber = Config.ResultNumber;
            var interests = Services.InterestService.GetInterests(pageNumber, resultsNumber);
            var model = interests.Select(i => new ViewInterestModel()
            {
                InterestId = i.IdInterest,
                Description = i.Description,
                Name = i.Name
            })
            .ToList();

            var pager = new Pager<ViewInterestModel>()
            {
                CurrentPageNumber = pageNumber,
                ElementList = model,
                ResultsPerPage = resultsNumber,
                TotalResultNumber = Services.InterestService.GetInterestCount()
            };

            if (pager.isEmptyPage())
            {
                if (pager.LastPageNumber > 0)
                    return RedirectToAction("List", new { pageNumber = pager.LastPageNumber });
                else
                    return View("List");
            }

            return View(pager);
        }

        [HttpGet]
        public ActionResult Create(int pageNumber = 1)
        {
            var model = new CreateInterestModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreateInterestModel model)
        {
            var newInterest = new Interest()
            {
                Name = model.Name,
                Description = model.Description
            };
            Services.InterestService.AddInterest(newInterest);

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var interes = Services.InterestService.GetInterestById(id);
            if (interes == null)
            {
                return HttpNotFound();
            }
            var model = new EditInterestModel()
            {
                InterestId = interes.IdInterest,
                Description = interes.Description,
                Name = interes.Name
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditInterestModel model)
        {
            var interest = new Interest()
            {
                Name = model.Name,
                IdInterest = model.InterestId,
                Description = model.Description
            };

            Services.InterestService.EditInterest(interest);
            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Delete(FormCollection form)
        {
            Services.InterestService.DeleteInterest(Convert.ToInt32(form["InterestId"]));
            return RedirectToAction("List");

        }
    }
}

WebClient/Views/Interest/Create.cshtml
@model Socializr.Models.Interest.CreateInterestModel

@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateInterestModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

WebClient/Views/Interest/Display.cshtml
@model Socializr.Models.Interest.ViewInterestModel

<tr>
    <td>
        @Html.DisplayFor(model => model.Name)
    </td>
    <td>
        @Html.DisplayFor(model => model.Description)
    </td>
    <td>
        @Html.ActionLink("Edit / Delete", "Edit", new { id = Model.InterestId })
    </td>
</tr>

WebClient/Views/Interest/Edit.cshtml
@model Socializr.Models.Interest.EditInterestModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EditInterestModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.InterestId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("Delete", "Interest", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.HiddenFor(model => model.InterestId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.InterestId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "List")
</div>

WebClient/Views/Interest/List.cshtml
@using Socializr.Code.Pagination
@using Socializr.Models.Interest
@using Socializr.Code.Helpers
@model  Pager<ViewInterestModel>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.ElementList.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ElementList.First().Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.ElementList)
    {
        @Html.Partial("Display", item)
    }
</table>

@Html.PageOptions(Model, "List")

@*@if (ViewBag.PageNumber > 1)
    {
        @Html.ActionLink("Previous", "List", new { pageNumber = ViewBag.PageNumber - 1 })
    }

    @Html.ActionLink("Next", "List", new { pageNumber = ViewBag.PageNumber + 1 })*@