WebClient/Models/Localities/AddCityModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Socializr.Models.Localities
{
    public class AddCityModel
    {
        [Required]
        public int CountyId { get; set; }

        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
    }
}

WebClient/Models/Localities/AddCountyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Socializr.Models.Localities
{
    public class CreateCountyModel
    {
        [Required]
        public string Name { get; set; }

        [MaxLength(2)]
        public string ShortName { get; set; }
    }
}

WebClient/Models/Localities/EditCityModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Socializr.Models.Localities
{
    public class EditCityModel
    {
        public int IdCity { get; set; }
        public string Name { get; set; }
    }
}

WebClient/Models/Localities/EditCountiesModel.cs
using BusinessEntities.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Socializr.Models.Localities
{
    public class ListCountyModel
    {
        public string CountyName { get; set; }
        public int CountyId { get; set; }
    }
}

WebClient/Models/Localities/EditCountyModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Socializr.Models.Localities
{
    public class EditCountyModel
    {
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(2)]
        public string ShortName { get; set; }

        [Required]
        public int CountyId { get; set; }
    }
}

WebClient/Models/Localities/ListCityModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Socializr.Models.Localities
{
    public class ListCityModel
    {
        [Required]
        public int CityId { get; set; }
        
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
    }
}

WebClient/Controllers/LocalitiesController.cs
using BusinessEntities.Entities;
using BusinessEntities.Enums;
using Socializr.Code.Attributes;
using Socializr.Code.Base;
using Socializr.Models.Localities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Socializr.Controllers
{
    [AuthorizePermissions(Permissions.ManageLocalities)]
    public class LocalitiesController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("ListCounty", new { pageNumber = 1 });
        }

        #region Counties CRUD

        [HttpGet]
        public ActionResult ListCounty(int pageNumber = 1)
        {
            var countyList = Services.LocalitiesService.GetCounties(pageNumber, Config.ResultNumber);
            var list = countyList
                .Select(c => new ListCountyModel()
                {
                    CountyId = c.IdCounty,
                    CountyName = c.Name,
                }).ToList();

            ViewBag.PageNumber = pageNumber;
            return View(list);
        }

        [HttpGet]
        public ActionResult CreateCounty()
        {
            var model = new CreateCountyModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateCounty(CreateCountyModel model)
        {
            var county = new County()
            {
                Name = model.Name,
                ShortName = model.ShortName
            };
            Services.LocalitiesService.AddCountyWithNoCities(county);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteCounty(FormCollection form)
        {
            Services.LocalitiesService.DeleteCounty(Convert.ToInt32(form["countyId"]));
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Edit County Name and Short Name
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult EditCounty(int id)
        {
            var county = Services.LocalitiesService.GetCounty(id);
            if (county == null)
            {
                return HttpNotFound();
            }

            var model = new EditCountyModel()
            {
                CountyId = county.IdCounty,
                Name = county.Name,
                ShortName = county.ShortName
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditCounty(EditCountyModel model)
        {
            if (ModelState.IsValid)
            {
                var updatedCounty = new County()
                {
                    Name = model.Name,
                    ShortName = model.ShortName,
                    IdCounty = model.CountyId
                };

                Services.LocalitiesService.UpdateCounty(updatedCounty);
            }

            return RedirectToAction("EditCounty", new { id = model.CountyId });
        }

        #endregion

        #region Cities CRUD

        /// <summary>
        /// Add city 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListCity(int id)
        {
            var cities = Services.LocalitiesService.GetCitiesByCountyId(id);
            var model = cities.Select(city => new ListCityModel()
            {
                CityId = city.IdCity,
                Name = city.Name
            }).ToList();
            ViewBag.CountyId = id;
            return View(model);
        }

        [HttpGet]
        public ActionResult AddCity(int id)
        {
            var model = new AddCityModel()
            {
                CountyId = id
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult AddCity(AddCityModel model)
        {
            if (ModelState.IsValid)
            {

                var newCity = new City()
                {
                    IdCounty = model.CountyId,
                    Name = model.Name,
                };
                Services.LocalitiesService.AddCity(newCity);
            }
            return RedirectToAction("EditCounty", new { id = model.CountyId });
        }

        /// <summary>
        /// Delete
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteCity(FormCollection form)
        {
            Services.LocalitiesService.DeleteCity(Convert.ToInt32(form["item.CityId"]));

            return RedirectToAction("EditCounty", new { id = Convert.ToInt32(form["CountyId"]) });
        }

        #endregion
    }
}

WebClient/Views/Localities/AddCity.cshtml
@model Socializr.Models.Localities.AddCityModel

@using (Html.BeginForm("AddCity") ) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" , placeholder = "Add new city" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.CountyId, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

WebClient/Views/Localities/CreateCounty.cshtml
@model Socializr.Models.Localities.CreateCountyModel

@{
    ViewBag.Title = "AddCounty";
}

<h2>AddCounty</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AddCountyModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        
        <div class="form-group">
            @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to counties list", "ListCounty")
</div>

WebClient/Views/Localities/EditCounty.cshtml
@model Socializr.Models.Localities.EditCountyModel

@{
    ViewBag.Title = "EditCounty";
}

<h2>@Model.Name</h2>
@using (Html.BeginForm("DeleteCounty", "Localities", FormMethod.Post))
{
    @Html.HiddenFor(model => model.CountyId, new { htmlAttributes = new { @class = "form-control" } })
    
        <div class="col-md-10">
            <input type="submit" value="Delete this county" class="btn btn-default" />
        </div>
}

<div class="col-md-6">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit County Information</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.CountyId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CountyId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save Changes" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

</div>

<div class="col-md-6">
    <h4>Add a new city</h4>
    <hr />
    @Html.Action("AddCity", new { id = Model.CountyId })
</div>

@Html.Action("ListCity", new { id = Model.CountyId })

WebClient/Views/Localities/ListCity.cshtml
@model IEnumerable<Socializr.Models.Localities.ListCityModel>

@{
    ViewBag.Title = "ListCity";
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @using (Html.BeginForm("DeleteCity", "Localities", FormMethod.Post))
                {
                    @Html.HiddenFor(model => item.CityId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.Hidden("CountyId", (object)ViewBag.CountyId.ToString(), new { htmlAttributes = new { @class = "form-control" } })
                    <div class="col-md-2">
                        <input type="submit" value="Delete city" class="btn btn-default" />
                    </div>
                }
            </td>
        </tr>
    }
</table>

WebClient/Views/Localities/ListCounty.cshtml
@model IEnumerable<Socializr.Models.Localities.ListCountyModel>

@{
    ViewBag.Title = "EditCounties";
}

<h2>EditCounties</h2>

@Html.ActionLink("Create a new county", "CreateCounty", null, new { @class = "btn btn-default" })


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CountyName)
        </th>
        
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CountyName)
            </td>
            
            <td>
                @Html.ActionLink("Edit County", "EditCounty", new { id = item.CountyId })
            </td>
        </tr>
    }
</table>


@if (ViewBag.PageNumber > 1)
{
    @Html.ActionLink("Previous", "ListCounty", new { pageNumber = ViewBag.PageNumber - 1 })
}

@Html.ActionLink("Next", "ListCounty", new { pageNumber = ViewBag.PageNumber + 1 })