WebClient/Controllers/CommentController.cs
using BusinessEntities.CustomTypes;
using BusinessEntities.CustomTypes.PostDisplay;
using BusinessEntities.Entities;
using Socializr.Code.Base;
using Socializr.Models.Comment;
using Socializr.Models.Post;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Socializr.Controllers
{
    public class CommentController : BaseController
    {
      
        [HttpPost]
        public ActionResult AddComment(CreateCommentModel model)
        {
            var comment = new Comment()
            {
                Body = model.Body,
                CreatedOn = DateTime.Now,
                IdPost = model.IdPost,
                IdUser = Session.CurrentUser.IdUser,
            };

            Services.CommentLikeService.AddComment(comment);
            return Json(new { success = true, responseText = "Comment successfuly sent!" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetLatestComment(int postId)
        {
            var c = Services.CommentLikeService.GetLatestComment(postId);
            var result = new
            {
                idAuthor = c.IdUser,
                body = c.Body,
                date = c.CreatedOn.ToShortDateString(),
                authorName = c.AuthorFullName
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public ActionResult GetComments(int postId, int pageNumber = 1)
        {
            var comments = Services.CommentLikeService.GetComments(postId, pageNumber, Config.CommentsPerLoad);
            //comments.Reverse();
            var result = comments.Select(c => new
            {
                idAuthor = c.IdUser,
                body = c.Body,
                date = c.CreatedOn.ToShortDateString(),
                authorName = c.AuthorFullName
            }).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

WebClient/Controllers/FeedController.cs
using BusinessEntities.CustomTypes.PostDisplay;
using BusinessEntities.Enums;
using Socializr.Code.Attributes;
using Socializr.Code.Base;
using Socializr.Code.Pagination;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Socializr.Controllers
{
    [AuthorizePermissions(Permissions.AccessPublicApp)]
    public class FeedController : BaseController
    {
        [HttpGet]
        public ActionResult UserPosts(int id, int pageNumber = 1)
        {
            var authorId = id;
            var viewerId = Session.CurrentUser.IdUser;
            var postList = Services.PostService.GetFeedByAuthor(authorId, viewerId, pageNumber, Config.ResultNumber);
            var pager = new Pager<DisplayPostModel>()
            {
                CurrentPageNumber = pageNumber,
                ElementList = postList,
                ResultsPerPage = Config.ResultNumber,
                TotalResultNumber = Services.PostService.GetPostCountByUser(authorId, viewerId)
            };

            if (pager.isEmptyPage())
            {
                if (pager.LastPageNumber > 0)
                    return RedirectToAction("UserPosts", new { id = id, pageNumber = pager.LastPageNumber });

                else
                    return View("UserHasNoPosts");
            }

            return View(pager);
        }

        [HttpGet]
        public ActionResult Feed(int pageNumber = 1)
        {
            var viewerId = Session.CurrentUser.IdUser;
            var postList = Services.PostService.GetFeedForViewer(viewerId, pageNumber, Config.ResultNumber);

            var pager = new Pager<DisplayPostModel>()
            {
                CurrentPageNumber = pageNumber,
                ElementList = postList,
                ResultsPerPage = Config.ResultNumber,
                TotalResultNumber = 100
            };

            if (pager.isEmptyPage())
            {
                if (pager.LastPageNumber > 0)
                    return RedirectToAction("Feed", new { pageNumber = 1 });
                else
                    return View("UserHasNoPosts");
            }
            return View(pager);
        }

        [HttpGet]
        public ActionResult GetFeedPosts(int pageNumber = 1)
        {
            var viewerId = Session.CurrentUser.IdUser;
            var postList = Services.PostService.GetFeedForViewer(viewerId, pageNumber, Config.ResultNumber);

            var resultList = postList.Select(p => new
            {
                body = p.Body,
                idPost = p.IdPost,
                title = p.Title,
                idAuthor = p.IdUser,
                authorName = p.AuthorFullName,
                date = p.CreatedOn.ToShortDateString().ToString(),
                likeCount = p.LikeCount,
                isLiked = p.IsLikedByCurrentUser,
            })
            .ToList();

            return Json(resultList, JsonRequestBehavior.AllowGet);

        }


    }
}

WebClient/Controllers/ProfileController.cs
using BusinessEntities.Entities;
using BusinessEntities.Enums;
using Socializr.Code.Attributes;
using Socializr.Code.Base;
using Socializr.Models.Profile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Socializr.Controllers
{
    [AuthorizePermissions(Permissions.AccessPublicApp)]
    public class ProfileController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("ViewProfile", new { id = Session.CurrentUser.IdUser });
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var userId = Session.CurrentUser.IdUser;
            var user = Services.UserService.GetUserById(userId);
            if (user == null)
            {
                return HttpNotFound();
            }
            var model = new EditProfileModel()
            {
                Birthday = user.Birthday,
                //Email = user.Email,
                FName = user.FName,
                LName = user.LName,
                IdCity = user.IdCity,
                IdCounty = user.IdCity == null ? (int?)null : user.City.IdCounty,
                IdUser = user.IdUser,
                IsMale = user.IsMale,
                IsPublic = user.IsPublic,
                CityName = user.City == null ? null : user.City.Name,
                SelectedInterests = Services.InterestService
                    .GetUserInterests(userId)
                    .Select(i => new SelectListItem()
                    {
                        Text = i.Name,
                        Value = i.IdInterest.ToString()
                    })
                    .ToList()
            };

            model.CountiesSelectItems = Services.LocalitiesService
                .GetCounties()
                .Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.IdCounty.ToString()
                })
                .ToList();

            model.CitiesSelectItems = new List<SelectListItem>();
            model.CitiesSelectItems.Add(new SelectListItem()
            {
                Text = model.CityName,
                Value = model.IdCity.ToString(),
            });

            //return Json(model, JsonRequestBehavior.AllowGet);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProfileModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User()
                {
                    Birthday = model.Birthday,
                    IdCity = model.IdCity,
                    FName = model.FName,
                    LName = model.LName,
                    IsMale = model.IsMale,
                    IsPublic = model.IsPublic ?? true,
                    IdUser = model.IdUser
                };
                //return Json(model, JsonRequestBehavior.AllowGet);
                Services.UserService.SaveUserChanges(user);
                Services.InterestService.SetInterestList(model.IdUser, model.InterestIds);

            }
            return RedirectToAction("Edit");
        }

        [HttpGet]
        public ActionResult ViewProfile(int id)
        {
            var user = Services.UserService.GetUserById(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            if (Services.UserService.HasAccessToProfile(id, Session.CurrentUser.IdUser))
            {
                var model = new ViewFullProfileModel()
                {
                    Birthday = user.Birthday,
                    CityName = user.City == null ? string.Empty : user.City.Name,
                    CountyName = user.City == null ? string.Empty : user.City.County.Name,
                    Email = user.Email,
                    FName = user.FName,
                    LName = user.LName,
                    IdUser = user.IdUser,
                    Interests = user.Interests.Select(i => i.Name).ToList(),
                    IdProfilePhoto = user.IdProfilePhoto ?? 0,
                    IsMale = user.IsMale,
                };
                return View("ViewProfile", model);
            }
            else
            {
                var model = new ViewMinimalProfileModel()
                {
                    IdProfilePhoto = user.IdProfilePhoto ?? 0,
                    FName = user.FName,
                    LName = user.LName,
                    IdUser = user.IdUser,
                };
                return View("ViewMinimalProfile", model);
            }
        }

        [HttpGet]
        public ActionResult SearchUsers(string query)
        {
            var list = Services.UserService.SearchUsers(query, Config.ResultNumber)
               .Select(user => new
               {
                   id = user.IdUser,
                   text = user.FName + " " + user.LName
               });
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

WebClient/Views/Feed/Display.cshtml
@{ Layout = null; }

@model BusinessEntities.CustomTypes.PostDisplay.DisplayPostModel

<div class="container display-post well" data-idPost="@Model.IdPost">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <h4>@Html.DisplayFor(model => model.Title)</h4>
        </div>

        <div class="col-sm-6 col-sm-offset-3">
            <h5>@Html.ActionLink(Model.AuthorFullName, "ViewProfile", "Profile", new { id = Model.IdUser }, null)</h5>
        </div>

        <div class="col-sm-6 col-sm-offset-3">
            <p>@Html.DisplayFor(model => model.Body)</p>
        </div>

        <div class="col-sm-6 col-sm-offset-3">
            <p>@Html.DisplayFor(model => model.CreatedOn)</p>
        </div>

        <div class="col-sm-2 col-sm-offset-3">
            @if (Model.IsLikedByCurrentUser ?? false)
            {
                <button class="btn btn-sm btn-set-like btn-dislike"><span class='glyphicon glyphicon-thumbs-down'></span> Dislike</button>
            }
            else
            {
                <button class="btn btn-sm btn-set-like btn-like"><span class='glyphicon glyphicon-thumbs-up'></span> Like</button>
            }
            <span class="like-count" data-count="@Model.LikeCount">@Model.LikeCount Likes</span>
        </div>

        <div class="col-sm-3">
            @Html.Partial("~/Views/Comment/CreateCommentForm.cshtml")
        </div>

        <div class="col-sm-6 col-sm-offset-3">
            <div>
                <button class="btn btn-load-comments">More comments</button>
                <button class="btn btn-hide-comments">Hide comments</button>
                <div class="comments-display" data-pageNumber="0">
                    @*Comments will go in here*@
                </div>
            
            
            </div>
        </div>
    </div>
</div>

WebClient/Views/Feed/Feed.cshtml
@model  Socializr.Code.Pagination.Pager<BusinessEntities.CustomTypes.PostDisplay.DisplayPostModel>
@using Socializr.Code.Helpers


@{
    ViewBag.Title = "UserPosts";
}

<h2>Your post feed</h2>

<div class="post-list" data-pagenumber="1">
    @foreach (var item in Model.ElementList)
    {
        @Html.Partial("Display", item)
    }
</div>

<div>
    <button id="btn-load-posts">Load more posts</button>
</div>

@section scripts {
    <script type="text/javascript">
        var globalInfo = {
            ajaxUrl: {
                addComment: "@Url.Action("AddComment","Comment")",
                displayCommentList: "@Url.Action("DisplayCommentList", "Comment")",
                getLatestComment: "@Url.Action("GetLatestComment","Comment")",
                getComments: "@Url.Action("GetComments", "Comment")",
                getFeedPosts: "@Url.Action("GetFeedPosts", "Feed")",
            },
        };
    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/FeedManager.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/Post.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/LikeablePost.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/CommentablePost.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/likeSystem.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/commentSystem.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/feedSystem.js")"></script>
}

@Html.Partial("FeedHandlebars")

WebClient/Views/Feed/FeedHandlebars.cshtml
@{ Layout = null; }
<script id="display-comment-template" type="text/x-handlebars-template">
    <div class="container comment-display">
        <div class="row">
            <div class="col-sm-6">
                <a href="@Url.Action("ViewProfile","Profile",null)/{{idAuthor}}">{{authorName}}</a>
                <span>{{body}}</span>
                <p>{{date}}</p>
            </div>
        </div>
    </div>
</script>

<script id="display-post-template" type="text/x-handlebars-template">
    <div class="container display-post well" data-idPost="{{idPost}}">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <h4>{{title}}</h4>
            </div>

            <div class="col-sm-6 col-sm-offset-3">
                <h5><a href="@Url.Action("ViewProfile","Profile")/{{idAuthor}}">{{authorName}}</a></h5>
            </div>

            <div class="col-sm-6 col-sm-offset-3">
                <p>{{body}}</p>
            </div>

            <div class="col-sm-6 col-sm-offset-3">
                <p>{{date}}</p>
            </div>

            <div class="col-sm-2 col-sm-offset-3 like-button-container" data-isliked="{{isLiked}}">
                <span class="like-count" data-count="{{likeCount}}">{{likeCount}} Likes</span>
            </div>
            <div class="col-sm-3">
                <form class="form-add-comment">
                    <div class="input-group">
                        <span class="input-group-btn ">
                            <input type="submit" value="Add" class="btn" />
                        </span>
                        <input type="text" class="form-control input-add-comment" placeholder="Add a comment...">
                    </div>
                </form>
            </div>
            <div class="col-sm-6 col-sm-offset-3">
                <div>
                    <button class="btn btn-load-comments">More comments</button>
                    <button class="btn btn-hide-comments">Hide comments</button>
                    <div class="comments-display" data-pageNumber="0">
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script id="like-button-template" type="text/x-handlebars-template">
    <button class="btn btn-sm btn-set-like btn-like"><span class='glyphicon glyphicon-thumbs-up'></span> Like</button>
</script>

<script id="dislike-button-template" type="text/x-handlebars-template">
    <button class="btn btn-sm btn-set-like btn-dislike"><span class='glyphicon glyphicon-thumbs-down'></span> Dislike</button>
</script>

WebClient/Views/Feed/UserHasNoPosts.cshtml
@{
    ViewBag.Title = "UserHasNoPosts";
}

<div class="jumbotron">
    <h1>Uoups!</h1>
    <p class="lead">Seems like this user hasn't posted anything yet</p>
</div>

WebClient/Views/Feed/UserPosts.cshtml
@model  Socializr.Code.Pagination.Pager<BusinessEntities.CustomTypes.PostDisplay.DisplayPostModel>
@using Socializr.Code.Helpers

@{
    ViewBag.Title = "UserPosts";
}

<h2>@Model.ElementList.First().AuthorFullName's posts</h2>

<div class="post-list">
    @foreach (var item in Model.ElementList)
    {
        @Html.Partial("Display", item)
    }
</div>

@section scripts {
    <script type="text/javascript">
        var globalInfo = {
            ajaxUrl: {
                addComment: "@Url.Action("AddComment","Comment")",
                displayCommentList: "@Url.Action("DisplayCommentList", "Comment")",
                getLatestComment: "@Url.Action("GetLatestComment","Comment")",
                getComments: "@Url.Action("GetComments", "Comment")",
            },
        };
    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/Post.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/LikeablePost.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/CommentablePost.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/likeSystem.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app/Feed/commentSystem.js")"></script>
}


@Html.Partial("FeedHandlebars");
@Html.PageOptions(Model, "UserPosts")